### ISSUE TITLE
UI for coverage property

### ISSUE THREAD

**Issue by grosscol** [mlibrary/umrdr#100] opened 2016-02-22 16:47 UTC
UI for coverage property needs to be designed & implemented.  Coverage is a date range.  See: http://dublincore.org/documents/dcmi-period/ for details.

Dependent on #99

**Comment by grosscol** [comment] 2016-03-11 14:55
dependent on #99

**Comment by justcolin** [comment] 2016-04-26 18:48
@grosscol: is this pretty much a duplicate of #324 (@jonearley's current project)?

**Comment by njaffer** [comment] 2016-04-28 17:30
As per our conversation today with Matt C, Amy, Jake, Ben and Jon, the UI will look like this:

![img_0658](https://cloud.githubusercontent.com/assets/12487929/14895165/49ef177a-0d45-11e6-93b9-ffa8dcc605a5.JPG)

**Comment by jonearley** [comment] 2016-04-28 20:23
@njaffer, @amyneeser, @bnhowell

Here is gif showing how the date created field could work with ranges.

![](http://g.recordit.co/PXwWChSoya.gif)

**Comment by jonearley** [comment] 2016-04-28 20:28
Reopened. I was reading this issue and hit close somehow. Whoops!

**Comment by njaffer** [comment] 2017-01-05 15:55
done

**Closed by njaffer** 2017-01-05 15:55 UTC
Labels: UI
